/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RejFecha;

import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;




/**
 *
 * @author IngAndreina
 */
public class RelojFechas extends javax.swing.JFrame {

    /**
     * Creates new form RelojFechas
     */
    public RelojFechas() {
        initComponents();
          this.setLocationRelativeTo(null);
        Calendar cal=Calendar.getInstance();
        
        String meses[]={"ENERO","FEBRERO","MARZO","ABRIL","MAYO","JUNIO","JULIO","AGOSTO","SEPTIEMBRE","OCTUBRE","NOVIEMBRE","DICIEMBRE"};
        String dias[]={"DOMINGO","LUNES","MARTES","MIERCOLES","JUEVES","VIERNES","SABADO"};
        
        String dia=cal.get(cal.DATE)+"";
        int diaSemana=cal.get(Calendar.DAY_OF_WEEK);
        int mes=cal.get(Calendar.MONTH);
        
        this.lbDiaS.setText(dias[diaSemana-1]);
        this.lbDia.setText(dia+"  de ");
        this.lbMes.setText(meses[mes]);
        
    }
    
    public class RelojDigital implements ActionListener{

       
        public void actionPerformed(ActionEvent ae) {
        GregorianCalendar tiempo=new GregorianCalendar();
        int hora,minutos,segundos;
        
        hora=tiempo.get(Calendar.HOUR_OF_DAY);
        minutos=tiempo.get(Calendar.MINUTE);
        segundos=tiempo.get(Calendar.SECOND);
        
        lbHora.setText(String.valueOf(hora));
        lbMinutos.setText(String.valueOf(minutos));
        lbSegundos.setText(String.valueOf(segundos));
        }
        
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbHora = new javax.swing.JLabel();
        lbMinutos = new javax.swing.JLabel();
        lbSegundos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbMes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbDiaS = new javax.swing.JLabel();
        lbDia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbHora.setFont(new java.awt.Font("Batang", 0, 36)); // NOI18N
        lbHora.setForeground(new java.awt.Color(255, 255, 255));
        lbHora.setText("00");
        lbHora.setToolTipText("");
        jPanel1.add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 50, 40));

        lbMinutos.setFont(new java.awt.Font("Batang", 0, 36)); // NOI18N
        lbMinutos.setForeground(new java.awt.Color(255, 255, 255));
        lbMinutos.setText("00");
        lbMinutos.setToolTipText("");
        jPanel1.add(lbMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 50, 40));

        lbSegundos.setFont(new java.awt.Font("Batang", 0, 36)); // NOI18N
        lbSegundos.setForeground(new java.awt.Color(255, 255, 255));
        lbSegundos.setText("00");
        lbSegundos.setToolTipText("");
        jPanel1.add(lbSegundos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 50, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setOpaque(true);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 1, 70));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setOpaque(true);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 1, 70));

        lbMes.setFont(new java.awt.Font("Batang", 0, 24)); // NOI18N
        lbMes.setForeground(new java.awt.Color(255, 255, 255));
        lbMes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbMes.setText("Mes");
        lbMes.setToolTipText("");
        jPanel1.add(lbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 120, 30));

        jLabel6.setFont(new java.awt.Font("Batang", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hora");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 50, 20));

        jLabel7.setFont(new java.awt.Font("Batang", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Minutos");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 80, 20));

        jLabel8.setFont(new java.awt.Font("Batang", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Segundos");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 80, 20));

        lbDiaS.setFont(new java.awt.Font("Batang", 0, 24)); // NOI18N
        lbDiaS.setForeground(new java.awt.Color(255, 255, 255));
        lbDiaS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDiaS.setText("DiaS");
        lbDiaS.setToolTipText("");
        jPanel1.add(lbDiaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 160, 30));

        lbDia.setFont(new java.awt.Font("Batang", 0, 24)); // NOI18N
        lbDia.setForeground(new java.awt.Color(255, 255, 255));
        lbDia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDia.setText("Dia");
        lbDia.setToolTipText("");
        jPanel1.add(lbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RejFecha/icons8-ajustes-26.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 30, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RejFecha/icons8-apagar-26.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 30, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RejFecha/new-york-fondos-pantalla-hd-31.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Timer timer;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      timer=new Timer(1000,new RelojDigital());
      timer.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelojFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelojFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelojFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelojFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelojFechas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbDia;
    private javax.swing.JLabel lbDiaS;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lbMinutos;
    private javax.swing.JLabel lbSegundos;
    // End of variables declaration//GEN-END:variables
}
